# Generated by Django 4.2.3 on 2023-07-30 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Housrapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='assigned_groups',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
